name: WPShop
main: bonana\Main
api: 4.0.0

version: 1.0.0
description: A shop plugin

permissions:
  shop.command:
    description: Open shop UI
    default: true
  xp.command.give:
    description: Give a player XP
    default: op
  xp.command:
    description: Check your XP
    default: true
